using System;
using System.Data;
using System.Data.SqlClient;

namespace TaskingSolutions.Data.DataAccess
{

    /*
     *   !!!DO NOT MODIFY THE CODE IN THIS FILE!!!
     *
     *
     *   It has been auto-generated by a scripting engine and is intended to be replaced with new
     *       auto-gen'd code should the need arise. Please use a separate partial class instead
     *
     *   The only modification that should be made to this file is to remove code where the functionality
     *       was replaced by code in the separate partial class
     */


    public abstract class AccessorBase
    {

        protected string ConnectionString { get; private set; }

        public AccessorBase(string connectionString)
        {
            this.ConnectionString = connectionString;
        }

        protected SqlParameter Parameter(string parameterName, SqlDbType type, object value)
        {
            SqlParameter result = new SqlParameter(parameterName, type);
            result.Value = value ?? DBNull.Value;
            return result;
        }

        protected SqlParameter OutputParameter(string parameterName, SqlDbType type)
        {
            SqlParameter result = new SqlParameter(parameterName, type);
            result.Direction = ParameterDirection.Output;
            return result;
        }

    }

}
