using System.Configuration;

namespace TaskingSolutions.Data.DataAccess
{

    /*
     *   !!!DO NOT MODIFY THE CODE IN THIS FILE!!!
     *
     *
     *   It has been auto-generated by a scripting engine and is intended to be replaced with new
     *       auto-gen'd code should the need arise. Please use a separate partial class instead
     *
     *   The only modification that should be made to this file is to remove code where the functionality
     *       was replaced by code in the separate partial class
     */


    public partial interface IDataAccessFactory
    {

        IDebugLogsAccessor GetDebugLogsAccessor();
        IErrorLogsAccessor GetErrorLogsAccessor();
        IJobRunsAccessor GetJobRunsAccessor();
        IJobRunStatsAccessor GetJobRunStatsAccessor();
        IJobRunStatTypesAccessor GetJobRunStatTypesAccessor();
        IJobsAccessor GetJobsAccessor();
        IJobSchedulesAccessor GetJobSchedulesAccessor();

    }


    public partial class DataAccessFactory : IDataAccessFactory
    {

         private string ConnectionString { get; set; }

         public DataAccessFactory(string connectionStringConfigKey)
         {
             if (ConfigurationManager.ConnectionStrings.Count == 0)
                 throw new ConfigurationErrorsException($"No connection string was found in the.config file");

             var conStr = ConfigurationManager.ConnectionStrings[connectionStringConfigKey];
             if (conStr == null)
                 throw new ConfigurationErrorsException($"Connection string with key {connectionStringConfigKey} was not found in the .config file");

             this.ConnectionString = conStr.ConnectionString;
         }

         public DataAccessFactory()
         {
             if (ConfigurationManager.ConnectionStrings.Count == 0)
                 throw new ConfigurationErrorsException($"No connection string was found in the.config file");

             var conStr = ConfigurationManager.ConnectionStrings["Default"] ?? ConfigurationManager.ConnectionStrings[0];
             this.ConnectionString = conStr.ConnectionString;
         }


        public IDebugLogsAccessor GetDebugLogsAccessor()
        {
            return new DebugLogsAccessor(this.ConnectionString);
        }

        public IErrorLogsAccessor GetErrorLogsAccessor()
        {
            return new ErrorLogsAccessor(this.ConnectionString);
        }

        public IJobRunsAccessor GetJobRunsAccessor()
        {
            return new JobRunsAccessor(this.ConnectionString);
        }

        public IJobRunStatsAccessor GetJobRunStatsAccessor()
        {
            return new JobRunStatsAccessor(this.ConnectionString);
        }

        public IJobRunStatTypesAccessor GetJobRunStatTypesAccessor()
        {
            return new JobRunStatTypesAccessor(this.ConnectionString);
        }

        public IJobsAccessor GetJobsAccessor()
        {
            return new JobsAccessor(this.ConnectionString);
        }

        public IJobSchedulesAccessor GetJobSchedulesAccessor()
        {
            return new JobSchedulesAccessor(this.ConnectionString);
        }

    }

}
