using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;

namespace TaskingSolutions.Data.DataAccess
{

    /*
     *   !!!DO NOT MODIFY THE CODE IN THIS FILE!!!
     *
     *
     *   It has been auto-generated by a scripting engine and is intended to be replaced with new
     *       auto-gen'd code should the need arise. Please use a separate partial class instead
     *
     *   The only modification that should be made to this file is to remove code where the functionality
     *       was replaced by code in the separate partial class
     */


    public partial interface IDataAccessFactory
    {

        IDebugLogsAccessor GetDebugLogsAccessor();
        IErrorLogsAccessor GetErrorLogsAccessor();
        IJobRunsAccessor GetJobRunsAccessor();
        IJobRunStatsAccessor GetJobRunStatsAccessor();
        IJobRunStatTypesAccessor GetJobRunStatTypesAccessor();
        IJobsAccessor GetJobsAccessor();
        IJobSchedulesAccessor GetJobSchedulesAccessor();

    }


    public partial class DataAccessFactory : IDataAccessFactory
    {

        public IDebugLogsAccessor GetDebugLogsAccessor()
        {
            return new DebugLogsAccessor();
        }

        public IErrorLogsAccessor GetErrorLogsAccessor()
        {
            return new ErrorLogsAccessor();
        }

        public IJobRunsAccessor GetJobRunsAccessor()
        {
            return new JobRunsAccessor();
        }

        public IJobRunStatsAccessor GetJobRunStatsAccessor()
        {
            return new JobRunStatsAccessor();
        }

        public IJobRunStatTypesAccessor GetJobRunStatTypesAccessor()
        {
            return new JobRunStatTypesAccessor();
        }

        public IJobsAccessor GetJobsAccessor()
        {
            return new JobsAccessor();
        }

        public IJobSchedulesAccessor GetJobSchedulesAccessor()
        {
            return new JobSchedulesAccessor();
        }

    }

}
