using System;

namespace TaskingSolutions.Data.Entities
{

    /*
     *   !!!DO NOT MODIFY THE CODE IN THIS FILE!!!
     *
     *
     *   It has been auto-generated by a scripting engine and is intended to be replaced with new
     *       auto-gen'd code should the need arise. Please use a separate partial class instead
     *
     *   The only modification that should be made to this file is to remove code where the functionality
     *       was replaced by code in the separate partial class
     */


    public partial class JobSchedule : EntityBase
    {
        public int Id { get; set; }
        public int JobId { get; set; }
        public DateTime? InitialTriggerTime { get; set; }
        public RecurranceType RecurrenceType { get; set; }
        public int? RecurrenceInterval { get; set; }
        public int? TimesToRecur { get; set; }
        public DateTime? RecurUntil { get; set; }
        public int TimesTriggered { get; set; }
        public DateTime? NextTriggerTime { get; set; }
    }
}
