using System;

namespace TaskingSolutions.Data.Entities
{

    /*
     *   !!!DO NOT MODIFY THE CODE IN THIS FILE!!!
     *
     *
     *   It has been auto-generated by a scripting engine and is intended to be replaced with new
     *       auto-gen'd code should the need arise. Please use a separate partial class instead
     *
     *   The only modification that should be made to this file is to remove code where the functionality
     *       was replaced by code in the separate partial class
     */


    public partial class SystemLog : EntityBase
    {
        public long Id { get; set; }
        public DateTime Timestamp { get; set; }
        public string Message { get; set; }
        public string AdditionalData { get; set; }
    }
}
