using TaskingSolutions.Data.Entities;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;

namespace TaskingSolutions.Data.DataAccess
{

    /*
     *   !!!DO NOT MODIFY THE CODE IN THIS FILE!!!
     *
     *
     *   It has been auto-generated by a scripting engine and is intended to be replaced with new
     *       auto-gen'd code should the need arise. Please use a separate partial class instead
     *
     *   The only modification that should be made to this file is to remove code where the functionality
     *       was replaced by code in the separate partial class
     */


    public partial interface IErrorLogsAccessor
    {

        void Insert(ErrorLog item);
        IOutputValueBinder Insert(SqlCommand cmd, ErrorLog item);
        List<ErrorLog> GetByPk(int? Id);
        List<ErrorLog> GetByPk(SqlCommand cmd, int? Id);
        void Update(ErrorLog item);
        void Update(SqlCommand cmd, ErrorLog item);
        void Delete(int Id);
        void Delete(SqlCommand cmd, int Id);
        void Upsert(ErrorLog item);

    }


    internal partial class ErrorLogsAccessor : IErrorLogsAccessor
    {

        public void Insert(ErrorLog item)
        {
            IOutputValueBinder result;

            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        result = Insert(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }

                result.Commit();
            }
        }

        public IOutputValueBinder Insert(SqlCommand cmd, ErrorLog item)
        {

            OutputValueBinder result = new OutputValueBinder(item);

            cmd.CommandText = "DECLARE @results TABLE ([Id] Int); INSERT INTO [dbo].[ErrorLogs] ([TimeStamp], [Message], [Exception]) OUTPUT Inserted.[Id] INTO @results VALUES (@TimeStamp, @Message, @Exception); SELECT @Id = [Id] FROM @results;";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();
            SqlParameter IdParam = cmd.Parameters.Add(SQL.OutputParameter("@Id", SqlDbType.Int));
            SqlParameter TimeStampParam = cmd.Parameters.Add(SQL.Parameter("@TimeStamp", SqlDbType.DateTime2, item.TimeStamp));
            SqlParameter MessageParam = cmd.Parameters.Add(SQL.Parameter("@Message", SqlDbType.VarChar, item.Message));
            SqlParameter ExceptionParam = cmd.Parameters.Add(SQL.Parameter("@Exception", SqlDbType.VarChar, item.Exception));

            cmd.ExecuteNonQuery();

            result.Add("IsNew", false);
            result.Add("Id", IdParam.Value);
            return result;
        }

        public List<ErrorLog> GetByPk(int? Id)
        {
            List<ErrorLog> result;

            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        result = GetByPk(cmd, Id);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }

            return result;
        }

        public List<ErrorLog> GetByPk(SqlCommand cmd, int? Id)
        {
            List<ErrorLog> result = new List<ErrorLog>();

            cmd.CommandText = "SELECT * FROM [dbo].[ErrorLogs] WHERE (@Id IS NULL OR [Id] = @Id)";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();
            cmd.Parameters.Add(SQL.Parameter("@Id", SqlDbType.Int, Id));

            using (SqlDataReader reader = cmd.ExecuteReader())
                if (reader.HasRows)
                {
                    int IdIndex = reader.GetOrdinal("Id");
                    int TimeStampIndex = reader.GetOrdinal("TimeStamp");
                    int MessageIndex = reader.GetOrdinal("Message");
                    int ExceptionIndex = reader.GetOrdinal("Exception");

                    while (reader.Read())
                    {
                        ErrorLog item = new ErrorLog();

                        item.IsNew = false;
                        item.Id = reader.GetInt32(IdIndex);
                        item.TimeStamp = reader.GetDateTime(TimeStampIndex);
                        item.Message = reader.GetString(MessageIndex).Trim();
                        if (!reader.IsDBNull(ExceptionIndex)) item.Exception = reader.GetString(ExceptionIndex).Trim();

                        result.Add(item);
                    }
                }

                return result;
            }

        public void Update(ErrorLog item)
        {
            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        Update(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }
        }

        public void Update(SqlCommand cmd, ErrorLog item)
        {
            cmd.CommandText = "UPDATE [dbo].[ErrorLogs] SET [TimeStamp] = @TimeStamp, [Message] = @Message, [Exception] = @Exception WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;

            cmd.Parameters.Clear();
            cmd.Parameters.Add(SQL.Parameter("@Id", SqlDbType.Int, item.Id));
            cmd.Parameters.Add(SQL.Parameter("@TimeStamp", SqlDbType.DateTime2, item.TimeStamp));
            cmd.Parameters.Add(SQL.Parameter("@Message", SqlDbType.VarChar, item.Message));
            cmd.Parameters.Add(SQL.Parameter("@Exception", SqlDbType.VarChar, item.Exception));

            cmd.ExecuteNonQuery();
        }

        public void Delete(int Id)
        {
            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        Delete(cmd, Id);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }
        }

        public void Delete(SqlCommand cmd, int Id)
        {
            cmd.CommandText = "DELETE FROM dbo.ErrorLogs WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;

            cmd.Parameters.Clear();
            cmd.Parameters.Add(SQL.Parameter("@Id", SqlDbType.Int, Id));

            cmd.ExecuteNonQuery();
        }

        public void Upsert(ErrorLog item)
        {
            IOutputValueBinder result = null;

            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;

                        if (item.IsNew)
                            result = Insert(cmd, item);
                        else
                            Update(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }

                if (result != null) result.Commit();
            }
        }

    }
}
