using TaskingSolutions.Data.Entities;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;

namespace TaskingSolutions.Data.DataAccess
{

    /*
     *   !!!DO NOT MODIFY THE CODE IN THIS FILE!!!
     *
     *
     *   It has been auto-generated by a scripting engine and is intended to be replaced with new
     *       auto-gen'd code should the need arise. Please use a separate partial class instead
     *
     *   The only modification that should be made to this file is to remove code where the functionality
     *       was replaced by code in the separate partial class
     */


    public partial interface IJobRunStatTypesAccessor
    {

        void Insert(JobRunStatType item);
        void Insert(List<JobRunStatType> items);
        IOutputValueBinder Insert(SqlCommand cmd, JobRunStatType item);
        List<JobRunStatType> GetAll();
        List<JobRunStatType> GetAll(SqlCommand cmd);
        JobRunStatType GetByPk(int Id);
        JobRunStatType GetByPk(SqlCommand cmd, int Id);
        void Update(JobRunStatType item);
        void Update(SqlCommand cmd, JobRunStatType item);
        void Delete(int Id);
        void Delete(SqlCommand cmd, int Id);
        void Upsert(JobRunStatType item);

    }


    internal partial class JobRunStatTypesAccessor : AccessorBase, IJobRunStatTypesAccessor
    {

        public JobRunStatTypesAccessor(string connectionString) : base(connectionString) { }


        public void Insert(JobRunStatType item)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    Insert(cmd, item).Commit();
            }
        }

        public void Insert(List<JobRunStatType> items)
        {
            List<IOutputValueBinder> results = new List<IOutputValueBinder>(items.Count);

            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;

                        foreach (var item in items)
                            results.Add(Insert(cmd, item));
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }

                foreach (var result in results)
                    result.Commit();
            }
        }

        public IOutputValueBinder Insert(SqlCommand cmd, JobRunStatType item)
        {

            OutputValueBinder result = new OutputValueBinder(item);

            cmd.CommandText = "DECLARE @results TABLE ([Id] Int); INSERT INTO [dbo].[JobRunStatTypes] ([Description]) OUTPUT Inserted.[Id] INTO @results VALUES (@Description); SELECT @Id = [Id] FROM @results;";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();
            SqlParameter IdParam = cmd.Parameters.Add(OutputParameter("@Id", SqlDbType.Int));
            SqlParameter DescriptionParam = cmd.Parameters.Add(Parameter("@Description", SqlDbType.VarChar, item.Description));

            cmd.ExecuteNonQuery();

            result.Add("IsNew", false);
            result.Add("Id", IdParam.Value);
            return result;
        }

        protected List<JobRunStatType> ReadRecords(SqlDataReader reader)
        {
            List<JobRunStatType> result = new List<JobRunStatType>();

            if (reader.HasRows)
            {
                int IdIndex = reader.GetOrdinal("Id");
                int DescriptionIndex = reader.GetOrdinal("Description");

                while (reader.Read())
                {
                    JobRunStatType item = new JobRunStatType();

                    item.IsNew = false;
                    item.Id = reader.GetInt32(IdIndex);
                    item.Description = reader.GetString(DescriptionIndex).Trim();

                    result.Add(item);
                }
            }

            return result;
        }

        public List<JobRunStatType> GetAll()
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    return GetAll(cmd);
            }
        }

        public List<JobRunStatType> GetAll(SqlCommand cmd)
        {
            cmd.CommandText = "SELECT * FROM [dbo].[JobRunStatTypes]";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();

            using (SqlDataReader reader = cmd.ExecuteReader())
                return ReadRecords(reader);
        }

        public JobRunStatType GetByPk(int Id)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    return GetByPk(cmd, Id);
            }
        }

        public JobRunStatType GetByPk(SqlCommand cmd, int Id)
        {
            cmd.CommandText = "SELECT * FROM [dbo].[JobRunStatTypes] WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();
            cmd.Parameters.Add(Parameter("@Id", SqlDbType.Int, Id));

            using (SqlDataReader reader = cmd.ExecuteReader())
            {
                List<JobRunStatType> result = ReadRecords(reader);
                return result.Count == 1 ? result[0] : null;
            }
        }

        public void Update(JobRunStatType item)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    Update(cmd, item);
            }
        }

        public void Update(List<JobRunStatType> items)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;

                        foreach (var item in items)
                            Update(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }
        }

        public void Update(SqlCommand cmd, JobRunStatType item)
        {
            cmd.CommandText = "UPDATE [dbo].[JobRunStatTypes] SET [Description] = @Description WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;

            cmd.Parameters.Clear();
            cmd.Parameters.Add(Parameter("@Id", SqlDbType.Int, item.Id));
            cmd.Parameters.Add(Parameter("@Description", SqlDbType.VarChar, item.Description));

            cmd.ExecuteNonQuery();
        }

        public void Delete(int Id)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        Delete(cmd, Id);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }
        }

        public void Delete(SqlCommand cmd, int Id)
        {
            cmd.CommandText = "DELETE FROM dbo.JobRunStatTypes WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;

            cmd.Parameters.Clear();
            cmd.Parameters.Add(Parameter("@Id", SqlDbType.Int, Id));

            cmd.ExecuteNonQuery();
        }

        public void Upsert(JobRunStatType item)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    if (item.IsNew)
                        Insert(cmd, item).Commit();
                    else
                        Update(cmd, item);
            }
        }

        public void Upsert(List<JobRunStatType> items)
        {
            List<IOutputValueBinder> results = new List<IOutputValueBinder>(items.Count);

            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;

                        foreach (var item in items)
                            if (item.IsNew)
                                results.Add(Insert(cmd, item));
                            else
                                Update(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }

                foreach (var result in results)
                    result.Commit();
            }
        }

    }
}
