using TaskingSolutions.Data.Entities;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;

namespace TaskingSolutions.Data.DataAccess
{

    /*
     *   !!!DO NOT MODIFY THE CODE IN THIS FILE!!!
     *
     *
     *   It has been auto-generated by a scripting engine and is intended to be replaced with new
     *       auto-gen'd code should the need arise. Please use a separate partial class instead
     *
     *   The only modification that should be made to this file is to remove code where the functionality
     *       was replaced by code in the separate partial class
     */


    public partial interface IJobRunStatTypesAccessor
    {

        void Insert(JobRunStatType item);
        IOutputValueBinder Insert(SqlCommand cmd, JobRunStatType item);
        List<JobRunStatType> GetByPk(int? Id);
        List<JobRunStatType> GetByPk(SqlCommand cmd, int? Id);
        void Update(JobRunStatType item);
        void Update(SqlCommand cmd, JobRunStatType item);
        void Delete(int Id);
        void Delete(SqlCommand cmd, int Id);
        void Upsert(JobRunStatType item);

    }


    internal partial class JobRunStatTypesAccessor : IJobRunStatTypesAccessor
    {

        public void Insert(JobRunStatType item)
        {
            IOutputValueBinder result;

            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        result = Insert(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }

                result.Commit();
            }
        }

        public IOutputValueBinder Insert(SqlCommand cmd, JobRunStatType item)
        {

            OutputValueBinder result = new OutputValueBinder(item);

            cmd.CommandText = "DECLARE @results TABLE ([Id] Int); INSERT INTO [dbo].[JobRunStatTypes] ([Description]) OUTPUT Inserted.[Id] INTO @results VALUES (@Description); SELECT @Id = [Id] FROM @results;";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();
            SqlParameter IdParam = cmd.Parameters.Add(SQL.OutputParameter("@Id", SqlDbType.Int));
            SqlParameter DescriptionParam = cmd.Parameters.Add(SQL.Parameter("@Description", SqlDbType.VarChar, item.Description));

            cmd.ExecuteNonQuery();

            result.Add("IsNew", false);
            result.Add("Id", IdParam.Value);
            return result;
        }

        public List<JobRunStatType> GetByPk(int? Id)
        {
            List<JobRunStatType> result;

            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        result = GetByPk(cmd, Id);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }

            return result;
        }

        public List<JobRunStatType> GetByPk(SqlCommand cmd, int? Id)
        {
            List<JobRunStatType> result = new List<JobRunStatType>();

            cmd.CommandText = "SELECT * FROM [dbo].[JobRunStatTypes] WHERE (@Id IS NULL OR [Id] = @Id)";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();
            cmd.Parameters.Add(SQL.Parameter("@Id", SqlDbType.Int, Id));

            using (SqlDataReader reader = cmd.ExecuteReader())
                if (reader.HasRows)
                {
                    int IdIndex = reader.GetOrdinal("Id");
                    int DescriptionIndex = reader.GetOrdinal("Description");

                    while (reader.Read())
                    {
                        JobRunStatType item = new JobRunStatType();

                        item.IsNew = false;
                        item.Id = reader.GetInt32(IdIndex);
                        item.Description = reader.GetString(DescriptionIndex).Trim();

                        result.Add(item);
                    }
                }

                return result;
            }

        public void Update(JobRunStatType item)
        {
            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        Update(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }
        }

        public void Update(SqlCommand cmd, JobRunStatType item)
        {
            cmd.CommandText = "UPDATE [dbo].[JobRunStatTypes] SET [Description] = @Description WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;

            cmd.Parameters.Clear();
            cmd.Parameters.Add(SQL.Parameter("@Id", SqlDbType.Int, item.Id));
            cmd.Parameters.Add(SQL.Parameter("@Description", SqlDbType.VarChar, item.Description));

            cmd.ExecuteNonQuery();
        }

        public void Delete(int Id)
        {
            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        Delete(cmd, Id);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }
        }

        public void Delete(SqlCommand cmd, int Id)
        {
            cmd.CommandText = "DELETE FROM dbo.JobRunStatTypes WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;

            cmd.Parameters.Clear();
            cmd.Parameters.Add(SQL.Parameter("@Id", SqlDbType.Int, Id));

            cmd.ExecuteNonQuery();
        }

        public void Upsert(JobRunStatType item)
        {
            IOutputValueBinder result = null;

            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;

                        if (item.IsNew)
                            result = Insert(cmd, item);
                        else
                            Update(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }

                if (result != null) result.Commit();
            }
        }

    }
}
