using TaskingSolutions.Data.Entities;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;

namespace TaskingSolutions.Data.DataAccess
{

    /*
     *   !!!DO NOT MODIFY THE CODE IN THIS FILE!!!
     *
     *
     *   It has been auto-generated by a scripting engine and is intended to be replaced with new
     *       auto-gen'd code should the need arise. Please use a separate partial class instead
     *
     *   The only modification that should be made to this file is to remove code where the functionality
     *       was replaced by code in the separate partial class
     */


    public partial interface IJobRunsAccessor
    {

        void Insert(JobRun item);
        IOutputValueBinder Insert(SqlCommand cmd, JobRun item);
        List<JobRun> GetByPk(int? Id);
        List<JobRun> GetByPk(SqlCommand cmd, int? Id);
        void Update(JobRun item);
        void Update(SqlCommand cmd, JobRun item);
        void Delete(int Id);
        void Delete(SqlCommand cmd, int Id);
        void Upsert(JobRun item);

    }


    internal partial class JobRunsAccessor : IJobRunsAccessor
    {

        public void Insert(JobRun item)
        {
            IOutputValueBinder result;

            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        result = Insert(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }

                result.Commit();
            }
        }

        public IOutputValueBinder Insert(SqlCommand cmd, JobRun item)
        {

            OutputValueBinder result = new OutputValueBinder(item);

            cmd.CommandText = "DECLARE @results TABLE ([Id] Int); INSERT INTO [dbo].[JobRuns] ([JobId], [StartTime], [EndTime]) OUTPUT Inserted.[Id] INTO @results VALUES (@JobId, @StartTime, @EndTime); SELECT @Id = [Id] FROM @results;";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();
            SqlParameter IdParam = cmd.Parameters.Add(SQL.OutputParameter("@Id", SqlDbType.Int));
            SqlParameter JobIdParam = cmd.Parameters.Add(SQL.Parameter("@JobId", SqlDbType.Int, item.JobId));
            SqlParameter StartTimeParam = cmd.Parameters.Add(SQL.Parameter("@StartTime", SqlDbType.DateTime2, item.StartTime));
            SqlParameter EndTimeParam = cmd.Parameters.Add(SQL.Parameter("@EndTime", SqlDbType.DateTime2, item.EndTime));

            cmd.ExecuteNonQuery();

            result.Add("IsNew", false);
            result.Add("Id", IdParam.Value);
            return result;
        }

        public List<JobRun> GetByPk(int? Id)
        {
            List<JobRun> result;

            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        result = GetByPk(cmd, Id);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }

            return result;
        }

        public List<JobRun> GetByPk(SqlCommand cmd, int? Id)
        {
            List<JobRun> result = new List<JobRun>();

            cmd.CommandText = "SELECT * FROM [dbo].[JobRuns] WHERE (@Id IS NULL OR [Id] = @Id)";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();
            cmd.Parameters.Add(SQL.Parameter("@Id", SqlDbType.Int, Id));

            using (SqlDataReader reader = cmd.ExecuteReader())
                if (reader.HasRows)
                {
                    int IdIndex = reader.GetOrdinal("Id");
                    int JobIdIndex = reader.GetOrdinal("JobId");
                    int StartTimeIndex = reader.GetOrdinal("StartTime");
                    int EndTimeIndex = reader.GetOrdinal("EndTime");

                    while (reader.Read())
                    {
                        JobRun item = new JobRun();

                        item.IsNew = false;
                        item.Id = reader.GetInt32(IdIndex);
                        item.JobId = reader.GetInt32(JobIdIndex);
                        if (!reader.IsDBNull(StartTimeIndex)) item.StartTime = reader.GetDateTime(StartTimeIndex);
                        if (!reader.IsDBNull(EndTimeIndex)) item.EndTime = reader.GetDateTime(EndTimeIndex);

                        result.Add(item);
                    }
                }

                return result;
            }

        public void Update(JobRun item)
        {
            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        Update(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }
        }

        public void Update(SqlCommand cmd, JobRun item)
        {
            cmd.CommandText = "UPDATE [dbo].[JobRuns] SET [JobId] = @JobId, [StartTime] = @StartTime, [EndTime] = @EndTime WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;

            cmd.Parameters.Clear();
            cmd.Parameters.Add(SQL.Parameter("@Id", SqlDbType.Int, item.Id));
            cmd.Parameters.Add(SQL.Parameter("@JobId", SqlDbType.Int, item.JobId));
            cmd.Parameters.Add(SQL.Parameter("@StartTime", SqlDbType.DateTime2, item.StartTime));
            cmd.Parameters.Add(SQL.Parameter("@EndTime", SqlDbType.DateTime2, item.EndTime));

            cmd.ExecuteNonQuery();
        }

        public void Delete(int Id)
        {
            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        Delete(cmd, Id);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }
        }

        public void Delete(SqlCommand cmd, int Id)
        {
            cmd.CommandText = "DELETE FROM dbo.JobRuns WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;

            cmd.Parameters.Clear();
            cmd.Parameters.Add(SQL.Parameter("@Id", SqlDbType.Int, Id));

            cmd.ExecuteNonQuery();
        }

        public void Upsert(JobRun item)
        {
            IOutputValueBinder result = null;

            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;

                        if (item.IsNew)
                            result = Insert(cmd, item);
                        else
                            Update(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }

                if (result != null) result.Commit();
            }
        }

    }
}
