using TaskingSolutions.Data.Entities;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;

namespace TaskingSolutions.Data.DataAccess
{

    /*
     *   !!!DO NOT MODIFY THE CODE IN THIS FILE!!!
     *
     *
     *   It has been auto-generated by a scripting engine and is intended to be replaced with new
     *       auto-gen'd code should the need arise. Please use a separate partial class instead
     *
     *   The only modification that should be made to this file is to remove code where the functionality
     *       was replaced by code in the separate partial class
     */


    public partial interface IJobRunsAccessor
    {

        void Insert(JobRun item);
        void Insert(List<JobRun> items);
        IOutputValueBinder Insert(SqlCommand cmd, JobRun item);
        List<JobRun> GetAll();
        List<JobRun> GetAll(SqlCommand cmd);
        JobRun GetByPk(int Id);
        JobRun GetByPk(SqlCommand cmd, int Id);
        void Update(JobRun item);
        void Update(List<JobRun> items);
        void Update(SqlCommand cmd, JobRun item);
        void Delete(int Id);
        void Delete(SqlCommand cmd, int Id);
        void Upsert(JobRun item);

    }


    internal partial class JobRunsAccessor : AccessorBase, IJobRunsAccessor
    {

        public JobRunsAccessor(string connectionString) : base(connectionString) { }


        public void Insert(JobRun item)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    Insert(cmd, item).Commit();
            }
        }

        public void Insert(List<JobRun> items)
        {
            List<IOutputValueBinder> results = new List<IOutputValueBinder>(items.Count);

            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;

                        foreach (var item in items)
                            results.Add(Insert(cmd, item));
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }

                foreach (var result in results)
                    result.Commit();
            }
        }

        public IOutputValueBinder Insert(SqlCommand cmd, JobRun item)
        {

            OutputValueBinder result = new OutputValueBinder(item);

            cmd.CommandText = "DECLARE @results TABLE ([Id] Int); INSERT INTO [dbo].[JobRuns] ([JobId], [StartTime], [EndTime], [IsErrored], [Error]) OUTPUT Inserted.[Id] INTO @results VALUES (@JobId, @StartTime, @EndTime, @IsErrored, @Error); SELECT @Id = [Id] FROM @results;";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();
            SqlParameter IdParam = cmd.Parameters.Add(OutputParameter("@Id", SqlDbType.Int));
            SqlParameter JobIdParam = cmd.Parameters.Add(Parameter("@JobId", SqlDbType.Int, item.JobId));
            SqlParameter StartTimeParam = cmd.Parameters.Add(Parameter("@StartTime", SqlDbType.DateTime2, item.StartTime));
            SqlParameter EndTimeParam = cmd.Parameters.Add(Parameter("@EndTime", SqlDbType.DateTime2, item.EndTime));
            SqlParameter IsErroredParam = cmd.Parameters.Add(Parameter("@IsErrored", SqlDbType.Bit, item.IsErrored));
            SqlParameter ErrorParam = cmd.Parameters.Add(Parameter("@Error", SqlDbType.VarChar, item.Error));

            cmd.ExecuteNonQuery();

            result.Add("IsNew", false);
            result.Add("Id", IdParam.Value);
            return result;
        }

        protected List<JobRun> ReadRecords(SqlDataReader reader)
        {
            List<JobRun> result = new List<JobRun>();

            if (reader.HasRows)
            {
                int IdIndex = reader.GetOrdinal("Id");
                int JobIdIndex = reader.GetOrdinal("JobId");
                int StartTimeIndex = reader.GetOrdinal("StartTime");
                int EndTimeIndex = reader.GetOrdinal("EndTime");
                int IsErroredIndex = reader.GetOrdinal("IsErrored");
                int ErrorIndex = reader.GetOrdinal("Error");

                while (reader.Read())
                {
                    JobRun item = new JobRun();

                    item.IsNew = false;
                    item.Id = reader.GetInt32(IdIndex);
                    item.JobId = reader.GetInt32(JobIdIndex);
                    item.StartTime = reader.GetDateTime(StartTimeIndex);
                    if (!reader.IsDBNull(EndTimeIndex)) item.EndTime = reader.GetDateTime(EndTimeIndex);
                    item.IsErrored = reader.GetBoolean(IsErroredIndex);
                    if (!reader.IsDBNull(ErrorIndex)) item.Error = reader.GetString(ErrorIndex).Trim();

                    result.Add(item);
                }
            }

            return result;
        }

        public List<JobRun> GetAll()
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    return GetAll(cmd);
            }
        }

        public List<JobRun> GetAll(SqlCommand cmd)
        {
            cmd.CommandText = "SELECT * FROM [dbo].[JobRuns]";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();

            using (SqlDataReader reader = cmd.ExecuteReader())
                return ReadRecords(reader);
        }

        public JobRun GetByPk(int Id)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    return GetByPk(cmd, Id);
            }
        }

        public JobRun GetByPk(SqlCommand cmd, int Id)
        {
            cmd.CommandText = "SELECT * FROM [dbo].[JobRuns] WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();
            cmd.Parameters.Add(Parameter("@Id", SqlDbType.Int, Id));

            using (SqlDataReader reader = cmd.ExecuteReader())
            {
                List<JobRun> result = ReadRecords(reader);
                return result.Count == 1 ? result[0] : null;
            }
        }

        public void Update(JobRun item)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    Update(cmd, item);
            }
        }

        public void Update(List<JobRun> items)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;

                        foreach (var item in items)
                            Update(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }
        }

        public void Update(SqlCommand cmd, JobRun item)
        {
            cmd.CommandText = "UPDATE [dbo].[JobRuns] SET [JobId] = @JobId, [StartTime] = @StartTime, [EndTime] = @EndTime, [IsErrored] = @IsErrored, [Error] = @Error WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;

            cmd.Parameters.Clear();
            cmd.Parameters.Add(Parameter("@Id", SqlDbType.Int, item.Id));
            cmd.Parameters.Add(Parameter("@JobId", SqlDbType.Int, item.JobId));
            cmd.Parameters.Add(Parameter("@StartTime", SqlDbType.DateTime2, item.StartTime));
            cmd.Parameters.Add(Parameter("@EndTime", SqlDbType.DateTime2, item.EndTime));
            cmd.Parameters.Add(Parameter("@IsErrored", SqlDbType.Bit, item.IsErrored));
            cmd.Parameters.Add(Parameter("@Error", SqlDbType.VarChar, item.Error));

            cmd.ExecuteNonQuery();
        }

        public void Delete(int Id)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        Delete(cmd, Id);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }
        }

        public void Delete(SqlCommand cmd, int Id)
        {
            cmd.CommandText = "DELETE FROM dbo.JobRuns WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;

            cmd.Parameters.Clear();
            cmd.Parameters.Add(Parameter("@Id", SqlDbType.Int, Id));

            cmd.ExecuteNonQuery();
        }

        public void Upsert(JobRun item)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    if (item.IsNew)
                        Insert(cmd, item).Commit();
                    else
                        Update(cmd, item);
            }
        }

        public void Upsert(List<JobRun> items)
        {
            List<IOutputValueBinder> results = new List<IOutputValueBinder>(items.Count);

            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;

                        foreach (var item in items)
                            if (item.IsNew)
                                results.Add(Insert(cmd, item));
                            else
                                Update(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }

                foreach (var result in results)
                    result.Commit();
            }
        }

    }
}
