using TaskingSolutions.Data.Entities;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;

namespace TaskingSolutions.Data.DataAccess
{

    /*
     *   !!!DO NOT MODIFY THE CODE IN THIS FILE!!!
     *
     *
     *   It has been auto-generated by a scripting engine and is intended to be replaced with new
     *       auto-gen'd code should the need arise. Please use a separate partial class instead
     *
     *   The only modification that should be made to this file is to remove code where the functionality
     *       was replaced by code in the separate partial class
     */


    public partial interface IJobRunStatsAccessor
    {

        void Insert(JobRunStat item);
        IOutputValueBinder Insert(SqlCommand cmd, JobRunStat item);
        List<JobRunStat> GetByPk(int? Id);
        List<JobRunStat> GetByPk(SqlCommand cmd, int? Id);
        void Update(JobRunStat item);
        void Update(SqlCommand cmd, JobRunStat item);
        void Delete(int Id);
        void Delete(SqlCommand cmd, int Id);
        void Upsert(JobRunStat item);

    }


    internal partial class JobRunStatsAccessor : IJobRunStatsAccessor
    {

        public void Insert(JobRunStat item)
        {
            IOutputValueBinder result;

            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        result = Insert(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }

                result.Commit();
            }
        }

        public IOutputValueBinder Insert(SqlCommand cmd, JobRunStat item)
        {

            OutputValueBinder result = new OutputValueBinder(item);

            cmd.CommandText = "DECLARE @results TABLE ([Id] Int); INSERT INTO [dbo].[JobRunStats] ([JobRunId], [JobRunStatTypeId], [Value]) OUTPUT Inserted.[Id] INTO @results VALUES (@JobRunId, @JobRunStatTypeId, @Value); SELECT @Id = [Id] FROM @results;";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();
            SqlParameter IdParam = cmd.Parameters.Add(SQL.OutputParameter("@Id", SqlDbType.Int));
            SqlParameter JobRunIdParam = cmd.Parameters.Add(SQL.Parameter("@JobRunId", SqlDbType.Int, item.JobRunId));
            SqlParameter JobRunStatTypeIdParam = cmd.Parameters.Add(SQL.Parameter("@JobRunStatTypeId", SqlDbType.Int, item.JobRunStatTypeId));
            SqlParameter ValueParam = cmd.Parameters.Add(SQL.Parameter("@Value", SqlDbType.VarChar, item.Value));

            cmd.ExecuteNonQuery();

            result.Add("IsNew", false);
            result.Add("Id", IdParam.Value);
            return result;
        }

        public List<JobRunStat> GetByPk(int? Id)
        {
            List<JobRunStat> result;

            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        result = GetByPk(cmd, Id);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }

            return result;
        }

        public List<JobRunStat> GetByPk(SqlCommand cmd, int? Id)
        {
            List<JobRunStat> result = new List<JobRunStat>();

            cmd.CommandText = "SELECT * FROM [dbo].[JobRunStats] WHERE (@Id IS NULL OR [Id] = @Id)";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();
            cmd.Parameters.Add(SQL.Parameter("@Id", SqlDbType.Int, Id));

            using (SqlDataReader reader = cmd.ExecuteReader())
                if (reader.HasRows)
                {
                    int IdIndex = reader.GetOrdinal("Id");
                    int JobRunIdIndex = reader.GetOrdinal("JobRunId");
                    int JobRunStatTypeIdIndex = reader.GetOrdinal("JobRunStatTypeId");
                    int ValueIndex = reader.GetOrdinal("Value");

                    while (reader.Read())
                    {
                        JobRunStat item = new JobRunStat();

                        item.IsNew = false;
                        item.Id = reader.GetInt32(IdIndex);
                        item.JobRunId = reader.GetInt32(JobRunIdIndex);
                        item.JobRunStatTypeId = reader.GetInt32(JobRunStatTypeIdIndex);
                        item.Value = reader.GetString(ValueIndex).Trim();

                        result.Add(item);
                    }
                }

                return result;
            }

        public void Update(JobRunStat item)
        {
            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        Update(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }
        }

        public void Update(SqlCommand cmd, JobRunStat item)
        {
            cmd.CommandText = "UPDATE [dbo].[JobRunStats] SET [JobRunId] = @JobRunId, [JobRunStatTypeId] = @JobRunStatTypeId, [Value] = @Value WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;

            cmd.Parameters.Clear();
            cmd.Parameters.Add(SQL.Parameter("@Id", SqlDbType.Int, item.Id));
            cmd.Parameters.Add(SQL.Parameter("@JobRunId", SqlDbType.Int, item.JobRunId));
            cmd.Parameters.Add(SQL.Parameter("@JobRunStatTypeId", SqlDbType.Int, item.JobRunStatTypeId));
            cmd.Parameters.Add(SQL.Parameter("@Value", SqlDbType.VarChar, item.Value));

            cmd.ExecuteNonQuery();
        }

        public void Delete(int Id)
        {
            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        Delete(cmd, Id);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }
        }

        public void Delete(SqlCommand cmd, int Id)
        {
            cmd.CommandText = "DELETE FROM dbo.JobRunStats WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;

            cmd.Parameters.Clear();
            cmd.Parameters.Add(SQL.Parameter("@Id", SqlDbType.Int, Id));

            cmd.ExecuteNonQuery();
        }

        public void Upsert(JobRunStat item)
        {
            IOutputValueBinder result = null;

            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;

                        if (item.IsNew)
                            result = Insert(cmd, item);
                        else
                            Update(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }

                if (result != null) result.Commit();
            }
        }

    }
}
