using TaskingSolutions.Data.Entities;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;

namespace TaskingSolutions.Data.DataAccess
{

    /*
     *   !!!DO NOT MODIFY THE CODE IN THIS FILE!!!
     *
     *
     *   It has been auto-generated by a scripting engine and is intended to be replaced with new
     *       auto-gen'd code should the need arise. Please use a separate partial class instead
     *
     *   The only modification that should be made to this file is to remove code where the functionality
     *       was replaced by code in the separate partial class
     */


    public partial interface IJobRunStatsAccessor
    {

        void Insert(JobRunStat item);
        void Insert(List<JobRunStat> items);
        IOutputValueBinder Insert(SqlCommand cmd, JobRunStat item);
        List<JobRunStat> GetAll();
        List<JobRunStat> GetAll(SqlCommand cmd);
        JobRunStat GetByPk(int Id);
        JobRunStat GetByPk(SqlCommand cmd, int Id);
        void Update(JobRunStat item);
        void Update(List<JobRunStat> items);
        void Update(SqlCommand cmd, JobRunStat item);
        void Delete(int Id);
        void Delete(SqlCommand cmd, int Id);
        void Upsert(JobRunStat item);

    }


    internal partial class JobRunStatsAccessor : AccessorBase, IJobRunStatsAccessor
    {

        public JobRunStatsAccessor(string connectionString) : base(connectionString) { }


        public void Insert(JobRunStat item)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    Insert(cmd, item).Commit();
            }
        }

        public void Insert(List<JobRunStat> items)
        {
            List<IOutputValueBinder> results = new List<IOutputValueBinder>(items.Count);

            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;

                        foreach (var item in items)
                            results.Add(Insert(cmd, item));
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }

                foreach (var result in results)
                    result.Commit();
            }
        }

        public IOutputValueBinder Insert(SqlCommand cmd, JobRunStat item)
        {

            OutputValueBinder result = new OutputValueBinder(item);

            cmd.CommandText = "DECLARE @results TABLE ([Id] Int); INSERT INTO [dbo].[JobRunStats] ([JobRunId], [JobRunStatTypeId], [Value]) OUTPUT Inserted.[Id] INTO @results VALUES (@JobRunId, @JobRunStatTypeId, @Value); SELECT @Id = [Id] FROM @results;";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();
            SqlParameter IdParam = cmd.Parameters.Add(OutputParameter("@Id", SqlDbType.Int));
            SqlParameter JobRunIdParam = cmd.Parameters.Add(Parameter("@JobRunId", SqlDbType.Int, item.JobRunId));
            SqlParameter JobRunStatTypeIdParam = cmd.Parameters.Add(Parameter("@JobRunStatTypeId", SqlDbType.Int, item.JobRunStatTypeId));
            SqlParameter ValueParam = cmd.Parameters.Add(Parameter("@Value", SqlDbType.VarChar, item.Value));

            cmd.ExecuteNonQuery();

            result.Add("IsNew", false);
            result.Add("Id", IdParam.Value);
            return result;
        }

        protected List<JobRunStat> ReadRecords(SqlDataReader reader)
        {
            List<JobRunStat> result = new List<JobRunStat>();

            if (reader.HasRows)
            {
                int IdIndex = reader.GetOrdinal("Id");
                int JobRunIdIndex = reader.GetOrdinal("JobRunId");
                int JobRunStatTypeIdIndex = reader.GetOrdinal("JobRunStatTypeId");
                int ValueIndex = reader.GetOrdinal("Value");

                while (reader.Read())
                {
                    JobRunStat item = new JobRunStat();

                    item.IsNew = false;
                    item.Id = reader.GetInt32(IdIndex);
                    item.JobRunId = reader.GetInt32(JobRunIdIndex);
                    item.JobRunStatTypeId = reader.GetInt32(JobRunStatTypeIdIndex);
                    item.Value = reader.GetString(ValueIndex).Trim();

                    result.Add(item);
                }
            }

            return result;
        }

        public List<JobRunStat> GetAll()
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    return GetAll(cmd);
            }
        }

        public List<JobRunStat> GetAll(SqlCommand cmd)
        {
            cmd.CommandText = "SELECT * FROM [dbo].[JobRunStats]";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();

            using (SqlDataReader reader = cmd.ExecuteReader())
                return ReadRecords(reader);
        }

        public JobRunStat GetByPk(int Id)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    return GetByPk(cmd, Id);
            }
        }

        public JobRunStat GetByPk(SqlCommand cmd, int Id)
        {
            cmd.CommandText = "SELECT * FROM [dbo].[JobRunStats] WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();
            cmd.Parameters.Add(Parameter("@Id", SqlDbType.Int, Id));

            using (SqlDataReader reader = cmd.ExecuteReader())
            {
                List<JobRunStat> result = ReadRecords(reader);
                return result.Count == 1 ? result[0] : null;
            }
        }

        public void Update(JobRunStat item)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    Update(cmd, item);
            }
        }

        public void Update(List<JobRunStat> items)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;

                        foreach (var item in items)
                            Update(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }
        }

        public void Update(SqlCommand cmd, JobRunStat item)
        {
            cmd.CommandText = "UPDATE [dbo].[JobRunStats] SET [JobRunId] = @JobRunId, [JobRunStatTypeId] = @JobRunStatTypeId, [Value] = @Value WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;

            cmd.Parameters.Clear();
            cmd.Parameters.Add(Parameter("@Id", SqlDbType.Int, item.Id));
            cmd.Parameters.Add(Parameter("@JobRunId", SqlDbType.Int, item.JobRunId));
            cmd.Parameters.Add(Parameter("@JobRunStatTypeId", SqlDbType.Int, item.JobRunStatTypeId));
            cmd.Parameters.Add(Parameter("@Value", SqlDbType.VarChar, item.Value));

            cmd.ExecuteNonQuery();
        }

        public void Delete(int Id)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        Delete(cmd, Id);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }
        }

        public void Delete(SqlCommand cmd, int Id)
        {
            cmd.CommandText = "DELETE FROM dbo.JobRunStats WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;

            cmd.Parameters.Clear();
            cmd.Parameters.Add(Parameter("@Id", SqlDbType.Int, Id));

            cmd.ExecuteNonQuery();
        }

        public void Upsert(JobRunStat item)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    if (item.IsNew)
                        Insert(cmd, item).Commit();
                    else
                        Update(cmd, item);
            }
        }

        public void Upsert(List<JobRunStat> items)
        {
            List<IOutputValueBinder> results = new List<IOutputValueBinder>(items.Count);

            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;

                        foreach (var item in items)
                            if (item.IsNew)
                                results.Add(Insert(cmd, item));
                            else
                                Update(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }

                foreach (var result in results)
                    result.Commit();
            }
        }

    }
}
