using TaskingSolutions.Data.Entities;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;

namespace TaskingSolutions.Data.DataAccess
{

    /*
     *   !!!DO NOT MODIFY THE CODE IN THIS FILE!!!
     *
     *
     *   It has been auto-generated by a scripting engine and is intended to be replaced with new
     *       auto-gen'd code should the need arise. Please use a separate partial class instead
     *
     *   The only modification that should be made to this file is to remove code where the functionality
     *       was replaced by code in the separate partial class
     */


    public partial interface IJobsAccessor
    {

        void Insert(Job item);
        IOutputValueBinder Insert(SqlCommand cmd, Job item);
        List<Job> GetByPk(int? Id);
        List<Job> GetByPk(SqlCommand cmd, int? Id);
        void Update(Job item);
        void Update(SqlCommand cmd, Job item);
        void Delete(int Id);
        void Delete(SqlCommand cmd, int Id);
        void Upsert(Job item);

    }


    internal partial class JobsAccessor : IJobsAccessor
    {

        public void Insert(Job item)
        {
            IOutputValueBinder result;

            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        result = Insert(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }

                result.Commit();
            }
        }

        public IOutputValueBinder Insert(SqlCommand cmd, Job item)
        {

            OutputValueBinder result = new OutputValueBinder(item);

            cmd.CommandText = "DECLARE @results TABLE ([Id] Int); INSERT INTO [dbo].[Jobs] ([Name], [IsSystemJob], [CanRunConcurrent], [QueueMultipleInstances], [OnShutdown], [JobQueuePriority], [AlertsEmailList], [AlertIfNotRunForXMinutes], [DotNetType], [IsDotNetTypeMissing]) OUTPUT Inserted.[Id] INTO @results VALUES (@Name, @IsSystemJob, @CanRunConcurrent, @QueueMultipleInstances, @OnShutdown, @JobQueuePriority, @AlertsEmailList, @AlertIfNotRunForXMinutes, @DotNetType, @IsDotNetTypeMissing); SELECT @Id = [Id] FROM @results;";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();
            SqlParameter IdParam = cmd.Parameters.Add(SQL.OutputParameter("@Id", SqlDbType.Int));
            SqlParameter NameParam = cmd.Parameters.Add(SQL.Parameter("@Name", SqlDbType.VarChar, item.Name));
            SqlParameter IsSystemJobParam = cmd.Parameters.Add(SQL.Parameter("@IsSystemJob", SqlDbType.Bit, item.IsSystemJob));
            SqlParameter CanRunConcurrentParam = cmd.Parameters.Add(SQL.Parameter("@CanRunConcurrent", SqlDbType.Bit, item.CanRunConcurrent));
            SqlParameter QueueMultipleInstancesParam = cmd.Parameters.Add(SQL.Parameter("@QueueMultipleInstances", SqlDbType.Bit, item.QueueMultipleInstances));
            SqlParameter OnShutdownParam = cmd.Parameters.Add(SQL.Parameter("@OnShutdown", SqlDbType.TinyInt, item.OnShutdown));
            SqlParameter JobQueuePriorityParam = cmd.Parameters.Add(SQL.Parameter("@JobQueuePriority", SqlDbType.TinyInt, (byte)item.JobQueuePriority));
            SqlParameter AlertsEmailListParam = cmd.Parameters.Add(SQL.Parameter("@AlertsEmailList", SqlDbType.VarChar, item.AlertsEmailList));
            SqlParameter AlertIfNotRunForXMinutesParam = cmd.Parameters.Add(SQL.Parameter("@AlertIfNotRunForXMinutes", SqlDbType.Decimal, item.AlertIfNotRunForXMinutes));
            SqlParameter DotNetTypeParam = cmd.Parameters.Add(SQL.Parameter("@DotNetType", SqlDbType.VarChar, item.DotNetType));
            SqlParameter IsDotNetTypeMissingParam = cmd.Parameters.Add(SQL.Parameter("@IsDotNetTypeMissing", SqlDbType.Bit, item.IsDotNetTypeMissing));

            cmd.ExecuteNonQuery();

            result.Add("IsNew", false);
            result.Add("Id", IdParam.Value);
            return result;
        }

        public List<Job> GetByPk(int? Id)
        {
            List<Job> result;

            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        result = GetByPk(cmd, Id);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }

            return result;
        }

        public List<Job> GetByPk(SqlCommand cmd, int? Id)
        {
            List<Job> result = new List<Job>();

            cmd.CommandText = "SELECT * FROM [dbo].[Jobs] WHERE (@Id IS NULL OR [Id] = @Id)";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();
            cmd.Parameters.Add(SQL.Parameter("@Id", SqlDbType.Int, Id));

            using (SqlDataReader reader = cmd.ExecuteReader())
                if (reader.HasRows)
                {
                    int IdIndex = reader.GetOrdinal("Id");
                    int NameIndex = reader.GetOrdinal("Name");
                    int IsSystemJobIndex = reader.GetOrdinal("IsSystemJob");
                    int CanRunConcurrentIndex = reader.GetOrdinal("CanRunConcurrent");
                    int QueueMultipleInstancesIndex = reader.GetOrdinal("QueueMultipleInstances");
                    int OnShutdownIndex = reader.GetOrdinal("OnShutdown");
                    int JobQueuePriorityIndex = reader.GetOrdinal("JobQueuePriority");
                    int AlertsEmailListIndex = reader.GetOrdinal("AlertsEmailList");
                    int AlertIfNotRunForXMinutesIndex = reader.GetOrdinal("AlertIfNotRunForXMinutes");
                    int DotNetTypeIndex = reader.GetOrdinal("DotNetType");
                    int IsDotNetTypeMissingIndex = reader.GetOrdinal("IsDotNetTypeMissing");

                    while (reader.Read())
                    {
                        Job item = new Job();

                        item.IsNew = false;
                        item.Id = reader.GetInt32(IdIndex);
                        item.Name = reader.GetString(NameIndex).Trim();
                        item.IsSystemJob = reader.GetBoolean(IsSystemJobIndex);
                        item.CanRunConcurrent = reader.GetBoolean(CanRunConcurrentIndex);
                        item.QueueMultipleInstances = reader.GetBoolean(QueueMultipleInstancesIndex);
                        item.OnShutdown = reader.GetByte(OnShutdownIndex);
                        item.JobQueuePriority = (TaskingSolutions.Interfaces.JobQueuePriority)reader.GetByte(JobQueuePriorityIndex);
                        if (!reader.IsDBNull(AlertsEmailListIndex)) item.AlertsEmailList = reader.GetString(AlertsEmailListIndex).Trim();
                        if (!reader.IsDBNull(AlertIfNotRunForXMinutesIndex)) item.AlertIfNotRunForXMinutes = reader.GetDecimal(AlertIfNotRunForXMinutesIndex);
                        item.DotNetType = reader.GetString(DotNetTypeIndex).Trim();
                        item.IsDotNetTypeMissing = reader.GetBoolean(IsDotNetTypeMissingIndex);

                        result.Add(item);
                    }
                }

                return result;
            }

        public void Update(Job item)
        {
            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        Update(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }
        }

        public void Update(SqlCommand cmd, Job item)
        {
            cmd.CommandText = "UPDATE [dbo].[Jobs] SET [Name] = @Name, [IsSystemJob] = @IsSystemJob, [CanRunConcurrent] = @CanRunConcurrent, [QueueMultipleInstances] = @QueueMultipleInstances, [OnShutdown] = @OnShutdown, [JobQueuePriority] = @JobQueuePriority, [AlertsEmailList] = @AlertsEmailList, [AlertIfNotRunForXMinutes] = @AlertIfNotRunForXMinutes, [DotNetType] = @DotNetType, [IsDotNetTypeMissing] = @IsDotNetTypeMissing WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;

            cmd.Parameters.Clear();
            cmd.Parameters.Add(SQL.Parameter("@Id", SqlDbType.Int, item.Id));
            cmd.Parameters.Add(SQL.Parameter("@Name", SqlDbType.VarChar, item.Name));
            cmd.Parameters.Add(SQL.Parameter("@IsSystemJob", SqlDbType.Bit, item.IsSystemJob));
            cmd.Parameters.Add(SQL.Parameter("@CanRunConcurrent", SqlDbType.Bit, item.CanRunConcurrent));
            cmd.Parameters.Add(SQL.Parameter("@QueueMultipleInstances", SqlDbType.Bit, item.QueueMultipleInstances));
            cmd.Parameters.Add(SQL.Parameter("@OnShutdown", SqlDbType.TinyInt, item.OnShutdown));
            cmd.Parameters.Add(SQL.Parameter("@JobQueuePriority", SqlDbType.TinyInt, (byte)item.JobQueuePriority));
            cmd.Parameters.Add(SQL.Parameter("@AlertsEmailList", SqlDbType.VarChar, item.AlertsEmailList));
            cmd.Parameters.Add(SQL.Parameter("@AlertIfNotRunForXMinutes", SqlDbType.Decimal, item.AlertIfNotRunForXMinutes));
            cmd.Parameters.Add(SQL.Parameter("@DotNetType", SqlDbType.VarChar, item.DotNetType));
            cmd.Parameters.Add(SQL.Parameter("@IsDotNetTypeMissing", SqlDbType.Bit, item.IsDotNetTypeMissing));

            cmd.ExecuteNonQuery();
        }

        public void Delete(int Id)
        {
            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        Delete(cmd, Id);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }
        }

        public void Delete(SqlCommand cmd, int Id)
        {
            cmd.CommandText = "DELETE FROM dbo.Jobs WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;

            cmd.Parameters.Clear();
            cmd.Parameters.Add(SQL.Parameter("@Id", SqlDbType.Int, Id));

            cmd.ExecuteNonQuery();
        }

        public void Upsert(Job item)
        {
            IOutputValueBinder result = null;

            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;

                        if (item.IsNew)
                            result = Insert(cmd, item);
                        else
                            Update(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }

                if (result != null) result.Commit();
            }
        }

    }
}
