using TaskingSolutions.Data.Entities;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;

namespace TaskingSolutions.Data.DataAccess
{

    /*
     *   !!!DO NOT MODIFY THE CODE IN THIS FILE!!!
     *
     *
     *   It has been auto-generated by a scripting engine and is intended to be replaced with new
     *       auto-gen'd code should the need arise. Please use a separate partial class instead
     *
     *   The only modification that should be made to this file is to remove code where the functionality
     *       was replaced by code in the separate partial class
     */


    public partial interface IJobSchedulesAccessor
    {

        void Insert(JobSchedule item);
        IOutputValueBinder Insert(SqlCommand cmd, JobSchedule item);
        List<JobSchedule> GetByPk(int? Id);
        List<JobSchedule> GetByPk(SqlCommand cmd, int? Id);
        void Update(JobSchedule item);
        void Update(SqlCommand cmd, JobSchedule item);
        void Delete(int Id);
        void Delete(SqlCommand cmd, int Id);
        void Upsert(JobSchedule item);

    }


    internal partial class JobSchedulesAccessor : IJobSchedulesAccessor
    {

        public void Insert(JobSchedule item)
        {
            IOutputValueBinder result;

            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        result = Insert(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }

                result.Commit();
            }
        }

        public IOutputValueBinder Insert(SqlCommand cmd, JobSchedule item)
        {

            OutputValueBinder result = new OutputValueBinder(item);

            cmd.CommandText = "DECLARE @results TABLE ([Id] Int); INSERT INTO [dbo].[JobSchedules] ([JobId], [InitialTriggerTime], [RecurrenceType], [RecurrenceInterval], [TimesToRecur], [RecurUntil], [TimesTriggered], [NextTriggerTime]) OUTPUT Inserted.[Id] INTO @results VALUES (@JobId, @InitialTriggerTime, @RecurrenceType, @RecurrenceInterval, @TimesToRecur, @RecurUntil, @TimesTriggered, @NextTriggerTime); SELECT @Id = [Id] FROM @results;";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();
            SqlParameter IdParam = cmd.Parameters.Add(SQL.OutputParameter("@Id", SqlDbType.Int));
            SqlParameter JobIdParam = cmd.Parameters.Add(SQL.Parameter("@JobId", SqlDbType.Int, item.JobId));
            SqlParameter InitialTriggerTimeParam = cmd.Parameters.Add(SQL.Parameter("@InitialTriggerTime", SqlDbType.DateTime2, item.InitialTriggerTime));
            SqlParameter RecurrenceTypeParam = cmd.Parameters.Add(SQL.Parameter("@RecurrenceType", SqlDbType.SmallInt, (short)item.RecurrenceType));
            SqlParameter RecurrenceIntervalParam = cmd.Parameters.Add(SQL.Parameter("@RecurrenceInterval", SqlDbType.Int, item.RecurrenceInterval));
            SqlParameter TimesToRecurParam = cmd.Parameters.Add(SQL.Parameter("@TimesToRecur", SqlDbType.Int, item.TimesToRecur));
            SqlParameter RecurUntilParam = cmd.Parameters.Add(SQL.Parameter("@RecurUntil", SqlDbType.DateTime2, item.RecurUntil));
            SqlParameter TimesTriggeredParam = cmd.Parameters.Add(SQL.Parameter("@TimesTriggered", SqlDbType.Int, item.TimesTriggered));
            SqlParameter NextTriggerTimeParam = cmd.Parameters.Add(SQL.Parameter("@NextTriggerTime", SqlDbType.DateTime2, item.NextTriggerTime));

            cmd.ExecuteNonQuery();

            result.Add("IsNew", false);
            result.Add("Id", IdParam.Value);
            return result;
        }

        public List<JobSchedule> GetByPk(int? Id)
        {
            List<JobSchedule> result;

            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        result = GetByPk(cmd, Id);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }

            return result;
        }

        public List<JobSchedule> GetByPk(SqlCommand cmd, int? Id)
        {
            List<JobSchedule> result = new List<JobSchedule>();

            cmd.CommandText = "SELECT * FROM [dbo].[JobSchedules] WHERE (@Id IS NULL OR [Id] = @Id)";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();
            cmd.Parameters.Add(SQL.Parameter("@Id", SqlDbType.Int, Id));

            using (SqlDataReader reader = cmd.ExecuteReader())
                if (reader.HasRows)
                {
                    int IdIndex = reader.GetOrdinal("Id");
                    int JobIdIndex = reader.GetOrdinal("JobId");
                    int InitialTriggerTimeIndex = reader.GetOrdinal("InitialTriggerTime");
                    int RecurrenceTypeIndex = reader.GetOrdinal("RecurrenceType");
                    int RecurrenceIntervalIndex = reader.GetOrdinal("RecurrenceInterval");
                    int TimesToRecurIndex = reader.GetOrdinal("TimesToRecur");
                    int RecurUntilIndex = reader.GetOrdinal("RecurUntil");
                    int TimesTriggeredIndex = reader.GetOrdinal("TimesTriggered");
                    int NextTriggerTimeIndex = reader.GetOrdinal("NextTriggerTime");

                    while (reader.Read())
                    {
                        JobSchedule item = new JobSchedule();

                        item.IsNew = false;
                        item.Id = reader.GetInt32(IdIndex);
                        item.JobId = reader.GetInt32(JobIdIndex);
                        if (!reader.IsDBNull(InitialTriggerTimeIndex)) item.InitialTriggerTime = reader.GetDateTime(InitialTriggerTimeIndex);
                        item.RecurrenceType = (RecurranceType)reader.GetInt16(RecurrenceTypeIndex);
                        if (!reader.IsDBNull(RecurrenceIntervalIndex)) item.RecurrenceInterval = reader.GetInt32(RecurrenceIntervalIndex);
                        if (!reader.IsDBNull(TimesToRecurIndex)) item.TimesToRecur = reader.GetInt32(TimesToRecurIndex);
                        if (!reader.IsDBNull(RecurUntilIndex)) item.RecurUntil = reader.GetDateTime(RecurUntilIndex);
                        item.TimesTriggered = reader.GetInt32(TimesTriggeredIndex);
                        if (!reader.IsDBNull(NextTriggerTimeIndex)) item.NextTriggerTime = reader.GetDateTime(NextTriggerTimeIndex);

                        result.Add(item);
                    }
                }

                return result;
            }

        public void Update(JobSchedule item)
        {
            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        Update(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }
        }

        public void Update(SqlCommand cmd, JobSchedule item)
        {
            cmd.CommandText = "UPDATE [dbo].[JobSchedules] SET [JobId] = @JobId, [InitialTriggerTime] = @InitialTriggerTime, [RecurrenceType] = @RecurrenceType, [RecurrenceInterval] = @RecurrenceInterval, [TimesToRecur] = @TimesToRecur, [RecurUntil] = @RecurUntil, [TimesTriggered] = @TimesTriggered, [NextTriggerTime] = @NextTriggerTime WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;

            cmd.Parameters.Clear();
            cmd.Parameters.Add(SQL.Parameter("@Id", SqlDbType.Int, item.Id));
            cmd.Parameters.Add(SQL.Parameter("@JobId", SqlDbType.Int, item.JobId));
            cmd.Parameters.Add(SQL.Parameter("@InitialTriggerTime", SqlDbType.DateTime2, item.InitialTriggerTime));
            cmd.Parameters.Add(SQL.Parameter("@RecurrenceType", SqlDbType.SmallInt, (short)item.RecurrenceType));
            cmd.Parameters.Add(SQL.Parameter("@RecurrenceInterval", SqlDbType.Int, item.RecurrenceInterval));
            cmd.Parameters.Add(SQL.Parameter("@TimesToRecur", SqlDbType.Int, item.TimesToRecur));
            cmd.Parameters.Add(SQL.Parameter("@RecurUntil", SqlDbType.DateTime2, item.RecurUntil));
            cmd.Parameters.Add(SQL.Parameter("@TimesTriggered", SqlDbType.Int, item.TimesTriggered));
            cmd.Parameters.Add(SQL.Parameter("@NextTriggerTime", SqlDbType.DateTime2, item.NextTriggerTime));

            cmd.ExecuteNonQuery();
        }

        public void Delete(int Id)
        {
            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        Delete(cmd, Id);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }
        }

        public void Delete(SqlCommand cmd, int Id)
        {
            cmd.CommandText = "DELETE FROM dbo.JobSchedules WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;

            cmd.Parameters.Clear();
            cmd.Parameters.Add(SQL.Parameter("@Id", SqlDbType.Int, Id));

            cmd.ExecuteNonQuery();
        }

        public void Upsert(JobSchedule item)
        {
            IOutputValueBinder result = null;

            using (SqlConnection con = new SqlConnection(SQL.ConStr))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;

                        if (item.IsNew)
                            result = Insert(cmd, item);
                        else
                            Update(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }

                if (result != null) result.Commit();
            }
        }

    }
}
