using TaskingSolutions.Data.Entities;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;

namespace TaskingSolutions.Data.DataAccess
{

    /*
     *   !!!DO NOT MODIFY THE CODE IN THIS FILE!!!
     *
     *
     *   It has been auto-generated by a scripting engine and is intended to be replaced with new
     *       auto-gen'd code should the need arise. Please use a separate partial class instead
     *
     *   The only modification that should be made to this file is to remove code where the functionality
     *       was replaced by code in the separate partial class
     */


    public partial interface IJobsAccessor
    {

        void Insert(Job item);
        void Insert(List<Job> items);
        IOutputValueBinder Insert(SqlCommand cmd, Job item);
        List<Job> GetAll();
        List<Job> GetAll(SqlCommand cmd);
        Job GetByPk(int Id);
        Job GetByPk(SqlCommand cmd, int Id);
        void Update(Job item);
        void Update(List<Job> items);
        void Update(SqlCommand cmd, Job item);
        void Delete(int Id);
        void Delete(SqlCommand cmd, int Id);
        void Upsert(Job item);

    }


    internal partial class JobsAccessor : AccessorBase, IJobsAccessor
    {

        public JobsAccessor(string connectionString) : base(connectionString) { }


        public void Insert(Job item)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    Insert(cmd, item).Commit();
            }
        }

        public void Insert(List<Job> items)
        {
            List<IOutputValueBinder> results = new List<IOutputValueBinder>(items.Count);

            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;

                        foreach (var item in items)
                            results.Add(Insert(cmd, item));
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }

                foreach (var result in results)
                    result.Commit();
            }
        }

        public IOutputValueBinder Insert(SqlCommand cmd, Job item)
        {

            OutputValueBinder result = new OutputValueBinder(item);

            cmd.CommandText = "DECLARE @results TABLE ([Id] Int); INSERT INTO [dbo].[Jobs] ([Name], [IsSystemJob], [CanRunConcurrent], [QueueMultipleInstances], [JobQueuePriority], [AlertsEmailList], [AlertIfNotRunForXMinutes], [DotNetType], [IsDotNetTypeMissing], [IsDisabled]) OUTPUT Inserted.[Id] INTO @results VALUES (@Name, @IsSystemJob, @CanRunConcurrent, @QueueMultipleInstances, @JobQueuePriority, @AlertsEmailList, @AlertIfNotRunForXMinutes, @DotNetType, @IsDotNetTypeMissing, @IsDisabled); SELECT @Id = [Id] FROM @results;";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();
            SqlParameter IdParam = cmd.Parameters.Add(OutputParameter("@Id", SqlDbType.Int));
            SqlParameter NameParam = cmd.Parameters.Add(Parameter("@Name", SqlDbType.VarChar, item.Name));
            SqlParameter IsSystemJobParam = cmd.Parameters.Add(Parameter("@IsSystemJob", SqlDbType.Bit, item.IsSystemJob));
            SqlParameter CanRunConcurrentParam = cmd.Parameters.Add(Parameter("@CanRunConcurrent", SqlDbType.Bit, item.CanRunConcurrent));
            SqlParameter QueueMultipleInstancesParam = cmd.Parameters.Add(Parameter("@QueueMultipleInstances", SqlDbType.Bit, item.QueueMultipleInstances));
            SqlParameter JobQueuePriorityParam = cmd.Parameters.Add(Parameter("@JobQueuePriority", SqlDbType.TinyInt, (byte)item.JobQueuePriority));
            SqlParameter AlertsEmailListParam = cmd.Parameters.Add(Parameter("@AlertsEmailList", SqlDbType.VarChar, item.AlertsEmailList));
            SqlParameter AlertIfNotRunForXMinutesParam = cmd.Parameters.Add(Parameter("@AlertIfNotRunForXMinutes", SqlDbType.Decimal, item.AlertIfNotRunForXMinutes));
            SqlParameter DotNetTypeParam = cmd.Parameters.Add(Parameter("@DotNetType", SqlDbType.VarChar, item.DotNetType));
            SqlParameter IsDotNetTypeMissingParam = cmd.Parameters.Add(Parameter("@IsDotNetTypeMissing", SqlDbType.Bit, item.IsDotNetTypeMissing));
            SqlParameter IsDisabledParam = cmd.Parameters.Add(Parameter("@IsDisabled", SqlDbType.Bit, item.IsDisabled));

            cmd.ExecuteNonQuery();

            result.Add("IsNew", false);
            result.Add("Id", IdParam.Value);
            return result;
        }

        protected List<Job> ReadRecords(SqlDataReader reader)
        {
            List<Job> result = new List<Job>();

            if (reader.HasRows)
            {
                int IdIndex = reader.GetOrdinal("Id");
                int NameIndex = reader.GetOrdinal("Name");
                int IsSystemJobIndex = reader.GetOrdinal("IsSystemJob");
                int CanRunConcurrentIndex = reader.GetOrdinal("CanRunConcurrent");
                int QueueMultipleInstancesIndex = reader.GetOrdinal("QueueMultipleInstances");
                int JobQueuePriorityIndex = reader.GetOrdinal("JobQueuePriority");
                int AlertsEmailListIndex = reader.GetOrdinal("AlertsEmailList");
                int AlertIfNotRunForXMinutesIndex = reader.GetOrdinal("AlertIfNotRunForXMinutes");
                int DotNetTypeIndex = reader.GetOrdinal("DotNetType");
                int IsDotNetTypeMissingIndex = reader.GetOrdinal("IsDotNetTypeMissing");
                int IsDisabledIndex = reader.GetOrdinal("IsDisabled");

                while (reader.Read())
                {
                    Job item = new Job();

                    item.IsNew = false;
                    item.Id = reader.GetInt32(IdIndex);
                    item.Name = reader.GetString(NameIndex).Trim();
                    item.IsSystemJob = reader.GetBoolean(IsSystemJobIndex);
                    item.CanRunConcurrent = reader.GetBoolean(CanRunConcurrentIndex);
                    item.QueueMultipleInstances = reader.GetBoolean(QueueMultipleInstancesIndex);
                    item.JobQueuePriority = (TaskingSolutions.Interfaces.JobQueuePriority)reader.GetByte(JobQueuePriorityIndex);
                    if (!reader.IsDBNull(AlertsEmailListIndex)) item.AlertsEmailList = reader.GetString(AlertsEmailListIndex).Trim();
                    if (!reader.IsDBNull(AlertIfNotRunForXMinutesIndex)) item.AlertIfNotRunForXMinutes = reader.GetDecimal(AlertIfNotRunForXMinutesIndex);
                    item.DotNetType = reader.GetString(DotNetTypeIndex).Trim();
                    item.IsDotNetTypeMissing = reader.GetBoolean(IsDotNetTypeMissingIndex);
                    item.IsDisabled = reader.GetBoolean(IsDisabledIndex);

                    result.Add(item);
                }
            }

            return result;
        }

        public List<Job> GetAll()
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    return GetAll(cmd);
            }
        }

        public List<Job> GetAll(SqlCommand cmd)
        {
            cmd.CommandText = "SELECT * FROM [dbo].[Jobs]";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();

            using (SqlDataReader reader = cmd.ExecuteReader())
                return ReadRecords(reader);
        }

        public Job GetByPk(int Id)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    return GetByPk(cmd, Id);
            }
        }

        public Job GetByPk(SqlCommand cmd, int Id)
        {
            cmd.CommandText = "SELECT * FROM [dbo].[Jobs] WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();
            cmd.Parameters.Add(Parameter("@Id", SqlDbType.Int, Id));

            using (SqlDataReader reader = cmd.ExecuteReader())
            {
                List<Job> result = ReadRecords(reader);
                return result.Count == 1 ? result[0] : null;
            }
        }

        public void Update(Job item)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    Update(cmd, item);
            }
        }

        public void Update(List<Job> items)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;

                        foreach (var item in items)
                            Update(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }
        }

        public void Update(SqlCommand cmd, Job item)
        {
            cmd.CommandText = "UPDATE [dbo].[Jobs] SET [Name] = @Name, [IsSystemJob] = @IsSystemJob, [CanRunConcurrent] = @CanRunConcurrent, [QueueMultipleInstances] = @QueueMultipleInstances, [JobQueuePriority] = @JobQueuePriority, [AlertsEmailList] = @AlertsEmailList, [AlertIfNotRunForXMinutes] = @AlertIfNotRunForXMinutes, [DotNetType] = @DotNetType, [IsDotNetTypeMissing] = @IsDotNetTypeMissing, [IsDisabled] = @IsDisabled WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;

            cmd.Parameters.Clear();
            cmd.Parameters.Add(Parameter("@Id", SqlDbType.Int, item.Id));
            cmd.Parameters.Add(Parameter("@Name", SqlDbType.VarChar, item.Name));
            cmd.Parameters.Add(Parameter("@IsSystemJob", SqlDbType.Bit, item.IsSystemJob));
            cmd.Parameters.Add(Parameter("@CanRunConcurrent", SqlDbType.Bit, item.CanRunConcurrent));
            cmd.Parameters.Add(Parameter("@QueueMultipleInstances", SqlDbType.Bit, item.QueueMultipleInstances));
            cmd.Parameters.Add(Parameter("@JobQueuePriority", SqlDbType.TinyInt, (byte)item.JobQueuePriority));
            cmd.Parameters.Add(Parameter("@AlertsEmailList", SqlDbType.VarChar, item.AlertsEmailList));
            cmd.Parameters.Add(Parameter("@AlertIfNotRunForXMinutes", SqlDbType.Decimal, item.AlertIfNotRunForXMinutes));
            cmd.Parameters.Add(Parameter("@DotNetType", SqlDbType.VarChar, item.DotNetType));
            cmd.Parameters.Add(Parameter("@IsDotNetTypeMissing", SqlDbType.Bit, item.IsDotNetTypeMissing));
            cmd.Parameters.Add(Parameter("@IsDisabled", SqlDbType.Bit, item.IsDisabled));

            cmd.ExecuteNonQuery();
        }

        public void Delete(int Id)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        Delete(cmd, Id);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }
        }

        public void Delete(SqlCommand cmd, int Id)
        {
            cmd.CommandText = "DELETE FROM dbo.Jobs WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;

            cmd.Parameters.Clear();
            cmd.Parameters.Add(Parameter("@Id", SqlDbType.Int, Id));

            cmd.ExecuteNonQuery();
        }

        public void Upsert(Job item)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    if (item.IsNew)
                        Insert(cmd, item).Commit();
                    else
                        Update(cmd, item);
            }
        }

        public void Upsert(List<Job> items)
        {
            List<IOutputValueBinder> results = new List<IOutputValueBinder>(items.Count);

            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;

                        foreach (var item in items)
                            if (item.IsNew)
                                results.Add(Insert(cmd, item));
                            else
                                Update(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }

                foreach (var result in results)
                    result.Commit();
            }
        }

    }
}
