using TaskingSolutions.Data.Entities;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;

namespace TaskingSolutions.Data.DataAccess
{

    /*
     *   !!!DO NOT MODIFY THE CODE IN THIS FILE!!!
     *
     *
     *   It has been auto-generated by a scripting engine and is intended to be replaced with new
     *       auto-gen'd code should the need arise. Please use a separate partial class instead
     *
     *   The only modification that should be made to this file is to remove code where the functionality
     *       was replaced by code in the separate partial class
     */


    public partial interface IJobSchedulesAccessor
    {

        void Insert(JobSchedule item);
        void Insert(List<JobSchedule> items);
        IOutputValueBinder Insert(SqlCommand cmd, JobSchedule item);
        List<JobSchedule> GetAll();
        List<JobSchedule> GetAll(SqlCommand cmd);
        JobSchedule GetByPk(int Id);
        JobSchedule GetByPk(SqlCommand cmd, int Id);
        void Update(JobSchedule item);
        void Update(List<JobSchedule> items);
        void Update(SqlCommand cmd, JobSchedule item);
        void Delete(int Id);
        void Delete(SqlCommand cmd, int Id);
        void Upsert(JobSchedule item);

    }


    internal partial class JobSchedulesAccessor : AccessorBase, IJobSchedulesAccessor
    {

        public JobSchedulesAccessor(string connectionString) : base(connectionString) { }


        public void Insert(JobSchedule item)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    Insert(cmd, item).Commit();
            }
        }

        public void Insert(List<JobSchedule> items)
        {
            List<IOutputValueBinder> results = new List<IOutputValueBinder>(items.Count);

            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;

                        foreach (var item in items)
                            results.Add(Insert(cmd, item));
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }

                foreach (var result in results)
                    result.Commit();
            }
        }

        public IOutputValueBinder Insert(SqlCommand cmd, JobSchedule item)
        {

            OutputValueBinder result = new OutputValueBinder(item);

            cmd.CommandText = "DECLARE @results TABLE ([Id] Int); INSERT INTO [dbo].[JobSchedules] ([JobId], [InitialTriggerTime], [RecurrenceType], [RecurrenceInterval], [TimesToRecur], [RecurUntil], [TimesTriggered], [NextTriggerTime]) OUTPUT Inserted.[Id] INTO @results VALUES (@JobId, @InitialTriggerTime, @RecurrenceType, @RecurrenceInterval, @TimesToRecur, @RecurUntil, @TimesTriggered, @NextTriggerTime); SELECT @Id = [Id] FROM @results;";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();
            SqlParameter IdParam = cmd.Parameters.Add(OutputParameter("@Id", SqlDbType.Int));
            SqlParameter JobIdParam = cmd.Parameters.Add(Parameter("@JobId", SqlDbType.Int, item.JobId));
            SqlParameter InitialTriggerTimeParam = cmd.Parameters.Add(Parameter("@InitialTriggerTime", SqlDbType.DateTime2, item.InitialTriggerTime));
            SqlParameter RecurrenceTypeParam = cmd.Parameters.Add(Parameter("@RecurrenceType", SqlDbType.SmallInt, (short)item.RecurrenceType));
            SqlParameter RecurrenceIntervalParam = cmd.Parameters.Add(Parameter("@RecurrenceInterval", SqlDbType.Int, item.RecurrenceInterval));
            SqlParameter TimesToRecurParam = cmd.Parameters.Add(Parameter("@TimesToRecur", SqlDbType.Int, item.TimesToRecur));
            SqlParameter RecurUntilParam = cmd.Parameters.Add(Parameter("@RecurUntil", SqlDbType.DateTime2, item.RecurUntil));
            SqlParameter TimesTriggeredParam = cmd.Parameters.Add(Parameter("@TimesTriggered", SqlDbType.Int, item.TimesTriggered));
            SqlParameter NextTriggerTimeParam = cmd.Parameters.Add(Parameter("@NextTriggerTime", SqlDbType.DateTime2, item.NextTriggerTime));

            cmd.ExecuteNonQuery();

            result.Add("IsNew", false);
            result.Add("Id", IdParam.Value);
            return result;
        }

        protected List<JobSchedule> ReadRecords(SqlDataReader reader)
        {
            List<JobSchedule> result = new List<JobSchedule>();

            if (reader.HasRows)
            {
                int IdIndex = reader.GetOrdinal("Id");
                int JobIdIndex = reader.GetOrdinal("JobId");
                int InitialTriggerTimeIndex = reader.GetOrdinal("InitialTriggerTime");
                int RecurrenceTypeIndex = reader.GetOrdinal("RecurrenceType");
                int RecurrenceIntervalIndex = reader.GetOrdinal("RecurrenceInterval");
                int TimesToRecurIndex = reader.GetOrdinal("TimesToRecur");
                int RecurUntilIndex = reader.GetOrdinal("RecurUntil");
                int TimesTriggeredIndex = reader.GetOrdinal("TimesTriggered");
                int NextTriggerTimeIndex = reader.GetOrdinal("NextTriggerTime");

                while (reader.Read())
                {
                    JobSchedule item = new JobSchedule();

                    item.IsNew = false;
                    item.Id = reader.GetInt32(IdIndex);
                    item.JobId = reader.GetInt32(JobIdIndex);
                    if (!reader.IsDBNull(InitialTriggerTimeIndex)) item.InitialTriggerTime = reader.GetDateTime(InitialTriggerTimeIndex);
                    item.RecurrenceType = (RecurranceType)reader.GetInt16(RecurrenceTypeIndex);
                    if (!reader.IsDBNull(RecurrenceIntervalIndex)) item.RecurrenceInterval = reader.GetInt32(RecurrenceIntervalIndex);
                    if (!reader.IsDBNull(TimesToRecurIndex)) item.TimesToRecur = reader.GetInt32(TimesToRecurIndex);
                    if (!reader.IsDBNull(RecurUntilIndex)) item.RecurUntil = reader.GetDateTime(RecurUntilIndex);
                    item.TimesTriggered = reader.GetInt32(TimesTriggeredIndex);
                    if (!reader.IsDBNull(NextTriggerTimeIndex)) item.NextTriggerTime = reader.GetDateTime(NextTriggerTimeIndex);

                    result.Add(item);
                }
            }

            return result;
        }

        public List<JobSchedule> GetAll()
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    return GetAll(cmd);
            }
        }

        public List<JobSchedule> GetAll(SqlCommand cmd)
        {
            cmd.CommandText = "SELECT * FROM [dbo].[JobSchedules]";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();

            using (SqlDataReader reader = cmd.ExecuteReader())
                return ReadRecords(reader);
        }

        public JobSchedule GetByPk(int Id)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    return GetByPk(cmd, Id);
            }
        }

        public JobSchedule GetByPk(SqlCommand cmd, int Id)
        {
            cmd.CommandText = "SELECT * FROM [dbo].[JobSchedules] WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();
            cmd.Parameters.Add(Parameter("@Id", SqlDbType.Int, Id));

            using (SqlDataReader reader = cmd.ExecuteReader())
            {
                List<JobSchedule> result = ReadRecords(reader);
                return result.Count == 1 ? result[0] : null;
            }
        }

        public void Update(JobSchedule item)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    Update(cmd, item);
            }
        }

        public void Update(List<JobSchedule> items)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;

                        foreach (var item in items)
                            Update(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }
        }

        public void Update(SqlCommand cmd, JobSchedule item)
        {
            cmd.CommandText = "UPDATE [dbo].[JobSchedules] SET [JobId] = @JobId, [InitialTriggerTime] = @InitialTriggerTime, [RecurrenceType] = @RecurrenceType, [RecurrenceInterval] = @RecurrenceInterval, [TimesToRecur] = @TimesToRecur, [RecurUntil] = @RecurUntil, [TimesTriggered] = @TimesTriggered, [NextTriggerTime] = @NextTriggerTime WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;

            cmd.Parameters.Clear();
            cmd.Parameters.Add(Parameter("@Id", SqlDbType.Int, item.Id));
            cmd.Parameters.Add(Parameter("@JobId", SqlDbType.Int, item.JobId));
            cmd.Parameters.Add(Parameter("@InitialTriggerTime", SqlDbType.DateTime2, item.InitialTriggerTime));
            cmd.Parameters.Add(Parameter("@RecurrenceType", SqlDbType.SmallInt, (short)item.RecurrenceType));
            cmd.Parameters.Add(Parameter("@RecurrenceInterval", SqlDbType.Int, item.RecurrenceInterval));
            cmd.Parameters.Add(Parameter("@TimesToRecur", SqlDbType.Int, item.TimesToRecur));
            cmd.Parameters.Add(Parameter("@RecurUntil", SqlDbType.DateTime2, item.RecurUntil));
            cmd.Parameters.Add(Parameter("@TimesTriggered", SqlDbType.Int, item.TimesTriggered));
            cmd.Parameters.Add(Parameter("@NextTriggerTime", SqlDbType.DateTime2, item.NextTriggerTime));

            cmd.ExecuteNonQuery();
        }

        public void Delete(int Id)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        Delete(cmd, Id);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }
        }

        public void Delete(SqlCommand cmd, int Id)
        {
            cmd.CommandText = "DELETE FROM dbo.JobSchedules WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;

            cmd.Parameters.Clear();
            cmd.Parameters.Add(Parameter("@Id", SqlDbType.Int, Id));

            cmd.ExecuteNonQuery();
        }

        public void Upsert(JobSchedule item)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    if (item.IsNew)
                        Insert(cmd, item).Commit();
                    else
                        Update(cmd, item);
            }
        }

        public void Upsert(List<JobSchedule> items)
        {
            List<IOutputValueBinder> results = new List<IOutputValueBinder>(items.Count);

            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;

                        foreach (var item in items)
                            if (item.IsNew)
                                results.Add(Insert(cmd, item));
                            else
                                Update(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }

                foreach (var result in results)
                    result.Commit();
            }
        }

    }
}
