using TaskingSolutions.Data.Entities;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;

namespace TaskingSolutions.Data.DataAccess
{

    /*
     *   !!!DO NOT MODIFY THE CODE IN THIS FILE!!!
     *
     *
     *   It has been auto-generated by a scripting engine and is intended to be replaced with new
     *       auto-gen'd code should the need arise. Please use a separate partial class instead
     *
     *   The only modification that should be made to this file is to remove code where the functionality
     *       was replaced by code in the separate partial class
     */


    public partial interface ISystemLogsAccessor
    {

        void Insert(SystemLog item);
        void Insert(List<SystemLog> items);
        IOutputValueBinder Insert(SqlCommand cmd, SystemLog item);
        List<SystemLog> GetAll();
        List<SystemLog> GetAll(SqlCommand cmd);
        SystemLog GetByPk(int Id);
        SystemLog GetByPk(SqlCommand cmd, int Id);
        void Update(SystemLog item);
        void Update(List<SystemLog> items);
        void Update(SqlCommand cmd, SystemLog item);
        void Delete(int Id);
        void Delete(SqlCommand cmd, int Id);
        void Upsert(SystemLog item);

    }


    internal partial class SystemLogsAccessor : AccessorBase, ISystemLogsAccessor
    {

        public SystemLogsAccessor(string connectionString) : base(connectionString) { }


        public void Insert(SystemLog item)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    Insert(cmd, item).Commit();
            }
        }

        public void Insert(List<SystemLog> items)
        {
            List<IOutputValueBinder> results = new List<IOutputValueBinder>(items.Count);

            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;

                        foreach (var item in items)
                            results.Add(Insert(cmd, item));
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }

                foreach (var result in results)
                    result.Commit();
            }
        }

        public IOutputValueBinder Insert(SqlCommand cmd, SystemLog item)
        {

            OutputValueBinder result = new OutputValueBinder(item);

            cmd.CommandText = "DECLARE @results TABLE ([Id] Int); INSERT INTO [dbo].[SystemLogs] ([Timestamp], [Message], [AdditionalData]) OUTPUT Inserted.[Id] INTO @results VALUES (@Timestamp, @Message, @AdditionalData); SELECT @Id = [Id] FROM @results;";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();
            SqlParameter IdParam = cmd.Parameters.Add(OutputParameter("@Id", SqlDbType.Int));
            SqlParameter TimestampParam = cmd.Parameters.Add(Parameter("@Timestamp", SqlDbType.DateTime2, item.Timestamp));
            SqlParameter MessageParam = cmd.Parameters.Add(Parameter("@Message", SqlDbType.VarChar, item.Message));
            SqlParameter AdditionalDataParam = cmd.Parameters.Add(Parameter("@AdditionalData", SqlDbType.VarChar, item.AdditionalData));

            cmd.ExecuteNonQuery();

            result.Add("IsNew", false);
            result.Add("Id", IdParam.Value);
            return result;
        }

        protected List<SystemLog> ReadRecords(SqlDataReader reader)
        {
            List<SystemLog> result = new List<SystemLog>();

            if (reader.HasRows)
            {
                int IdIndex = reader.GetOrdinal("Id");
                int TimestampIndex = reader.GetOrdinal("Timestamp");
                int MessageIndex = reader.GetOrdinal("Message");
                int AdditionalDataIndex = reader.GetOrdinal("AdditionalData");

                while (reader.Read())
                {
                    SystemLog item = new SystemLog();

                    item.IsNew = false;
                    item.Id = reader.GetInt32(IdIndex);
                    item.Timestamp = reader.GetDateTime(TimestampIndex);
                    item.Message = reader.GetString(MessageIndex).Trim();
                    if (!reader.IsDBNull(AdditionalDataIndex)) item.AdditionalData = reader.GetString(AdditionalDataIndex).Trim();

                    result.Add(item);
                }
            }

            return result;
        }

        public List<SystemLog> GetAll()
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    return GetAll(cmd);
            }
        }

        public List<SystemLog> GetAll(SqlCommand cmd)
        {
            cmd.CommandText = "SELECT * FROM [dbo].[SystemLogs]";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();

            using (SqlDataReader reader = cmd.ExecuteReader())
                return ReadRecords(reader);
        }

        public SystemLog GetByPk(int Id)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    return GetByPk(cmd, Id);
            }
        }

        public SystemLog GetByPk(SqlCommand cmd, int Id)
        {
            cmd.CommandText = "SELECT * FROM [dbo].[SystemLogs] WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;
            cmd.Parameters.Clear();
            cmd.Parameters.Add(Parameter("@Id", SqlDbType.Int, Id));

            using (SqlDataReader reader = cmd.ExecuteReader())
            {
                List<SystemLog> result = ReadRecords(reader);
                return result.Count == 1 ? result[0] : null;
            }
        }

        public void Update(SystemLog item)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    Update(cmd, item);
            }
        }

        public void Update(List<SystemLog> items)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;

                        foreach (var item in items)
                            Update(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }
        }

        public void Update(SqlCommand cmd, SystemLog item)
        {
            cmd.CommandText = "UPDATE [dbo].[SystemLogs] SET [Timestamp] = @Timestamp, [Message] = @Message, [AdditionalData] = @AdditionalData WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;

            cmd.Parameters.Clear();
            cmd.Parameters.Add(Parameter("@Id", SqlDbType.Int, item.Id));
            cmd.Parameters.Add(Parameter("@Timestamp", SqlDbType.DateTime2, item.Timestamp));
            cmd.Parameters.Add(Parameter("@Message", SqlDbType.VarChar, item.Message));
            cmd.Parameters.Add(Parameter("@AdditionalData", SqlDbType.VarChar, item.AdditionalData));

            cmd.ExecuteNonQuery();
        }

        public void Delete(int Id)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;
                        Delete(cmd, Id);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }
            }
        }

        public void Delete(SqlCommand cmd, int Id)
        {
            cmd.CommandText = "DELETE FROM dbo.SystemLogs WHERE [Id] = @Id";
            cmd.CommandType = CommandType.Text;

            cmd.Parameters.Clear();
            cmd.Parameters.Add(Parameter("@Id", SqlDbType.Int, Id));

            cmd.ExecuteNonQuery();
        }

        public void Upsert(SystemLog item)
        {
            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();

                using (SqlCommand cmd = new SqlCommand(null, con))
                    if (item.IsNew)
                        Insert(cmd, item).Commit();
                    else
                        Update(cmd, item);
            }
        }

        public void Upsert(List<SystemLog> items)
        {
            List<IOutputValueBinder> results = new List<IOutputValueBinder>(items.Count);

            using (SqlConnection con = new SqlConnection(this.ConnectionString))
            {
                con.Open();
                SqlTransaction txn = con.BeginTransaction();

                try
                {
                    using (SqlCommand cmd = new SqlCommand(null, con))
                    {
                        cmd.Transaction = txn;

                        foreach (var item in items)
                            if (item.IsNew)
                                results.Add(Insert(cmd, item));
                            else
                                Update(cmd, item);
                    }

                    txn.Commit();
                }
                catch
                {
                    txn.Rollback();
                    throw;
                }

                foreach (var result in results)
                    result.Commit();
            }
        }

    }
}
